spring.application.name=WorkHub
spring.profiles.active=dev

spring.elasticsearch.uris=${ELASTICSEARCH_URIS:http://localhost:9200}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

workhub.queue.exchange=workhub.exchange
workhub.queue.email-queue=email.queue
workhub.queue.ats-screening-queue=ats.screening.queue
workhub.queue.resume-parsing-queue=resume.parsing.queue
workhub.queue.notification-queue=notification.queue
workhub.queue.email-dlq=email.dlq
workhub.queue.ats-screening-dlq=ats.screening.dlq
workhub.queue.resume-parsing-dlq=resume.parsing.dlq
workhub.queue.notification-dlq=notification.dlq
workhub.queue.retry.max-attempts=3

search.job.index-name=workhub_jobs
search.job.fuzzy-enabled=true
search.job.autocomplete-limit=10
search.job.fallback-to-jpa=true

recommendation.weights.content=0.50
recommendation.weights.behavior=0.30
recommendation.weights.collaborative=0.20
recommendation.behavior.view-weight=1
recommendation.behavior.click-weight=3
recommendation.behavior.save-weight=5
recommendation.behavior.apply-weight=10
recommendation.behavior.search-keyword-weight=2
recommendation.behavior.history-days=30
recommendation.collaborative.similar-user-limit=20
recommendation.collaborative.min-similarity=0.25
recommendation.result.max-candidates=200
recommendation.result.default-page-size=10
