spring.application.name=WorkHub
spring.profiles.active=dev

spring.elasticsearch.uris=${ELASTICSEARCH_URIS:http://localhost:9200}

search.job.index-name=workhub_jobs
search.job.fuzzy-enabled=true
search.job.autocomplete-limit=10
search.job.fallback-to-jpa=true
