package org.example.workhub.constant;

public enum RecommendationReasonCode {
    MATCHED_SKILL,
    MATCHED_TITLE,
    MATCHED_LOCATION,
    MATCHED_WORK_MODE,
    MATCHED_EMPLOYMENT_TYPE,
    MATCHED_EXPERIENCE,
    MATCHED_SALARY,
    BASED_ON_VIEW_HISTORY,
    BASED_ON_CLICK_HISTORY,
    BASED_ON_SAVED_JOBS,
    BASED_ON_APPLIED_JOBS,
    BASED_ON_SEARCH_KEYWORD,
    USERS_LIKE_YOU_APPLIED,
    USERS_LIKE_YOU_SAVED
}
